version: '3'
services:
  sql_db:
    container_name: 'sql-database'
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    env_file:
      - sql.env
    volumes:
      - ./dump:/docker-entrypoint-initdb.d